name: '${project.name}'
version: '${project.version}'
main: me.kteq.hiddenarmor.HiddenArmor
api-version: 1.16

authors: [ Kteq, Snoop1CattZ69 ]

description: Let players hide their armor and show off their skins
depend: [ProtocolLib, MC-OpenLibrary]

folia-supported: true
